# Publish the joint states to joint_states.
joint_state_ctrlr:
  type: joint_state_controller/JointStateController
  publish_rate: 30

left_steering_ctrlr:
  joint: left_steering_joint
  type: effort_controllers/JointPositionController
  pid: {p: 4.0, i: 0.0, d: 1.0}
right_steering_ctrlr:
  joint: right_steering_joint
  type: effort_controllers/JointPositionController
  pid: {p: 4.0, i: 0.0, d: 1.0}

left_front_axle_ctrlr:
  joint: left_front_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1.5, i: 0.0, d: 0.0, i_clamp: 10.0}
right_front_axle_ctrlr:
  joint: right_front_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1.5, i: 0.0, d: 0.0, i_clamp: 10.0}
left_rear_axle_ctrlr:
  joint: left_rear_axle
  type: effort_controllers/JointVelocityController
  pid: {p: 1.5, i: 0.0, d: 0.0, i_clamp: 10.0}
right_rear_axle_ctrlr:
  type: effort_controllers/JointVelocityController
  joint: right_rear_axle
  pid: {p: 1.5, i: 0.0, d: 0.0, i_clamp: 10.0}
body_to_hokuyo_mesh_ctrl:
  type: velocity_controllers/JointVelocityController
  joint: body_to_hokuyo_mesh_joint
  pid: {p: 1.5, i: 0.0, d: 0.0, i_clamp: 10.0}
