<?xml version="1.0"?>

<robot name="agent" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find hamster_vehicle_description)/urdf/wheel.urdf.xacro" />

    <xacro:macro name="solid_cuboid_inertia" params="w h d m"> 
    <inertia  ixx="${m*(h*h+d*d)/12}" ixy = "0" ixz = "0"
              iyy="${m*(w*w+d*d)/12}" iyz = "0"
              izz="${m*(w*w+h*h)/12}" /> 
    </xacro:macro>

  <link name="base_link">
    <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="1.0" />
        <solid_cuboid_inertia w="0.1" h="0.1" d="0.2" m="1.0"/>
    </inertial>
    <surface>
        <friction>
          <ode>
            <mu>1.0</mu>
            <mu2>1.0</mu2>
          </ode>
        </friction>
    </surface>
    <visual>
        <origin xyz="0 0 0.01" rpy="0 0 0" />
        <geometry>
            <mesh filename="package://hamster_vehicle_description/meshes/shell.dae" />
        </geometry>
    </visual>
    <collision>
        <origin xyz="-0.010 0 0.05"/>
        <geometry>
            <box size="0.25 0.09 0.05" />
        </geometry>
    </collision>
  </link>

  <link name="imu_link">
        <inertial>
            <mass value="0.01" />
            <solid_cuboid_inertia w="0.05" h="0.05" d="0.07" m="0.01"/>
        </inertial>
        <visual>
            <geometry>
                <box size="0.01 0.01 0.01" />
            </geometry>
        </visual>
    </link>

    <joint name="imu_link_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child  link="imu_link" />
    </joint>

      <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="0 0 ${height3 - axel_offset/2}" rpy="0 0 0"/>
    <parent link="link3"/>
    <child link="hokuyo_link"/>
  </joint>

  <!-- Hokuyo Laser -->
  <link name="lidar_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
    <box size="0.05 0.05 0.05"/>
      </geometry>
    </collision>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://hamster_vehicle_description/meshes/rp_lidar_head.dae" />
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>

  <wheel fr="front" lr="right" parent="base_link" origin_x="0.08" origin_y="-0.086" origin_z="0.03"/>
  <wheel fr="front" lr="left" parent="base_link" origin_x="0.08" origin_y="0.086" origin_z="0.03"/>
  <wheel fr="rear" lr="right" parent="base_link" origin_x="-0.085" origin_y="-0.086" origin_z="0.03"/>
  <wheel fr="rear" lr="left" parent="base_link" origin_x="-0.085" origin_y="0.086" origin_z="0.03"/> 

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/</robotNamespace>
        <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
        <legacyModeNS>true</legacyModeNS>
    </plugin>
  </gazebo>

            <!-- Skid steer drive controller -->
  <gazebo>
      <plugin name="skid_steer_drive_controller" filename="libgazebo_ros_skid_steer_drive.so">
          <alwaysOn>1</alwaysOn>
          <updateRate>100.0</updateRate>
          <robotNamespace>/</robotNamespace>
          <leftFrontJoint>front_left_wheel_joint</leftFrontJoint>
          <rightFrontJoint>front_right_wheel_joint</rightFrontJoint>
          <leftRearJoint>rear_left_wheel_joint</leftRearJoint>
          <rightRearJoint>rear_right_wheel_joint</rightRearJoint>
          <wheelSeparation>0.18</wheelSeparation>
          <wheelDiameter>0.058</wheelDiameter>
          <torque>50</torque>
          <broadcastTF>0</broadcastTF>
          <odometryFrame>map</odometryFrame>
          <commandTopic>cmd_vel</commandTopic>
          <odometryTopic>odom</odometryTopic>
          <robotBaseFrame>base_link</robotBaseFrame>
          <covariance_x>0.0001</covariance_x>
          <covariance_y>0.0001</covariance_y>
          <covariance_z>0.0001</covariance_z>
          <covariance_yaw>0.0001</covariance_yaw>
      </plugin>
  </gazebo>

  <gazebo reference="imu_link">
    <gravity>true</gravity>
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <update_rate>100</update_rate>
      <visualize>true</visualize>
      <topic>__default_topic__</topic>
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <topicName>sensors/imu_raw</topicName>
        <bodyName>imu_link</bodyName>
        <updateRateHZ>10.0</updateRateHZ>
        <gaussianNoise>0.0</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 0</rpyOffset>
        <frameName>imu_link</frameName>
      </plugin>
    </sensor>
  </gazebo>


</robot>
